spring.application.name=verify-email
server.port=8080

#servidor smtp , protocolo de envio de email do gmail(padrao para envio de emails)
spring.mail.host=smtp.gmail.com
#porta padrao do servidor smtp do gmail
spring.mail.port=587
#email remetente que sera usado para enviar o codigo de verificacao
spring.mail.username=experience.verificacao@gmail.com
spring.mail.password=udhh ixkp kxap qnro

# configurações adicionais para o envio de email
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
